name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x
      - name: install dependencies
        run: yarn install --flozen-lockfile
      - name: test
        run: yarn test:ci
      - name: Codecov Node
        run: bash <(curl -s https://codecov.io/bash)
      - name: build and publish
        run: yarn build && yarn publish
        if: contains(github.ref, 'tags/v')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
